In [1]:
import seaborn as sns
import numpy as np
import pandas as pd
import pandas as pd
import numpy as np
from decision_tree import DT
from sklearn.metrics import confusion_matrix




In [2]:
# data = pd.read_csv('./tests_datasets/testing.csv')
# data = pd.read_csv('./tests_datasets/iris.csv')
# data = iris

data = sns.load_dataset('iris')

data_train = data.sample(frac=0.7, random_state=43)
data_test = data[~data.index.isin(data_train.index)]



# print(data_train.head())
# print(data_train.shape)
# print(data_test.shape)
# print(data.shape)
# data_test = data[data.index.isin(data_train)]
clases = {elem for elem in data_train['species']}
id_of_class = {}

_id = 0
for class_ in clases:
    id_of_class[class_]  = _id
    _id += 1




update_clases = np.vectorize(lambda x: id_of_class[x])
X_train = data_train.drop(columns='species').to_numpy()
Y_train = data_train['species'].to_numpy()
Y_train = update_clases(Y_train)


X_test = data_test.drop(columns='species').to_numpy()
Y_test = data_test['species'].to_numpy()
Y_test = update_clases(Y_test)



In [3]:
print(Y_test)
print(data_test['species'].to_numpy())
print(clases)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1]
['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'virginica' 'virginica' 'virginica' 'virginica' 'virginica'
 'virginica' 'virginica' 'virginica' 'virginica' 'virginica' 'virginica'
 'virginica' 'virginica' 'virginica']
{'setosa', 'virginica', 'versicolor'}


In [4]:
dt = DT(X_train,Y_train)


In [5]:
a = confusion_matrix(Y_test,dt.predict(X_test))
print(a)
print(confusion_matrix(Y_train,dt.predict(X_train)))

# total_elems = a[0][0] + a[0][1] + a[1][0] + a[1][1]

# print( (a[0][0] + a[1][1]) / total_elems )


[[15  0  0]
 [ 0 14  1]
 [ 0  0 15]]
[[35  0  0]
 [ 0 35  0]
 [ 0  0 35]]


In [7]:
pred = dt.predict(X_train)
# print(Y_train)

for i in range(len(Y_train)):
    if pred[i] != Y_train[i]:
        print(X_train[i],i)
